### PR TITLE
Update For SBT 1.0.3, Slick 3.2.1, Scala 2.12

### PR DESCRIPTION
**Pull request by reid-spencer**
This PR upgrades the project to use Slick 3.2.1 which is built with Scala 2.12 and SBT 1.x.  It also:
* modernizes dependencies (pgp, sonatype)
* removes sbt-scalariform which doesn't work with sbt 1.x
* sets the version to 1.3.1-SNAPSHOT and updates documentation
* removes all the generated build files from the project subdirectories
* Uses the new Slick 3.2.1 names for profiles (slick.jdbc not slick.driver)

### CODE REVIEW

**Comment by hepin1989** [comment]
Yes， please merge and do  a release @tototoshi ,thank you very much.

**Comment by tototoshi** [comment]
Thanks but I can't merge this pull request because this contains files in .idea directory.
Please send a new pull request without .idea files if you can.

**Comment by tototoshi** [comment]
I will also try to modernize it

**Comment by hepin1989** [comment]
I see ,I have do a local publish for the datasource one,will try to do a PR once you update:)

**Pull request closed without merging**
